trigger:
  - master

pool:
  name: 'LocalAgentPool'

variables:
  javaHome: 'C:\Program Files\Java\jdk-21'
  mavenHome: 'C:\Program Files\Apache\Maven'

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:
      - job: Build
        displayName: 'Build Project'
        steps:
          - powershell: |
              Write-Host "Setting up environment variables..."
              [Environment]::SetEnvironmentVariable("JAVA_HOME", "${{ variables.javaHome }}", "Process")
              [Environment]::SetEnvironmentVariable("Path", "${{ variables.javaHome }}\bin;" + [Environment]::GetEnvironmentVariable("Path", "Process"), "Process")
              [Environment]::SetEnvironmentVariable("M2_HOME", "${{ variables.mavenHome }}", "Process")
              [Environment]::SetEnvironmentVariable("Path", "${{ variables.mavenHome }}\bin;" + [Environment]::GetEnvironmentVariable("Path", "Process"), "Process")
              
              Write-Host "Checking Java installation..."
              java -version
              Write-Host "Checking Maven installation..."
              & "${{ variables.mavenHome }}\bin\mvn.cmd" -version
            displayName: 'Set Up Java and Maven'

          - powershell: |
              Write-Host "Building Maven Project..."
              & "${{ variables.mavenHome }}\bin\mvn.cmd" clean install
              Write-Host "Maven Build completed successfully."
            displayName: 'Build with Maven'

          - powershell: |
              Write-Host "Running Tests..."
              & "${{ variables.mavenHome }}\bin\mvn.cmd" test
              Write-Host "Tests completed successfully."
            displayName: 'Run Tests'

          # Publicar el artefacto WAR
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)\target' # Ruta donde Maven genera el WAR
              artifact: 'build'
              publishLocation: 'pipeline'
